name: Build macOS DMG

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build macOS DMG
        run: npx electron-builder --mac --publish never

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HearMeRead-macOS-dmg
          path: dist/**
